import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { notFound } from "next/navigation";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";

import { routing } from "@/i18n/routing";

import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// TODO: replace with buildMetadata() once src/lib/seo/metadata.ts exists. Copy
// must come from src/content/ (hard rule 1), so this stays scaffold for now.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/** Pre-renders both locales at build time — the site is fully static. */
export function generateStaticParams(): Array<{ locale: string }> {
  return routing.locales.map((locale) => ({ locale }));
}

/**
 * Root layout. `[locale]` is the only top-level segment, so this is the
 * document shell for every page.
 */
export default async function LocaleLayout({
  children,
  params,
}: LayoutProps<"/[locale]">) {
  const { locale } = await params;

  // The segment is a catch-all, so an unknown value can land here.
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Opts this route into static rendering; without it the whole tree turns
  // dynamic as soon as a translation is read.
  setRequestLocale(locale);

  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
